<div class="min-h-screen bg-slate-950 text-slate-100">
    <div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:py-12">
        @if(session('approval-message'))<div class="mb-6 rounded-2xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-sm font-semibold text-emerald-200">{{ session('approval-message') }}</div>@endif
        <div class="relative overflow-hidden rounded-3xl border border-white/10 bg-white/[0.055] p-6 shadow-2xl backdrop-blur-2xl sm:p-8"><div class="pointer-events-none absolute -right-20 -top-32 h-72 w-72 rounded-full bg-emerald-500/15 blur-3xl"></div><div class="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-300">Centre de validation</p><h1 class="mt-3 text-3xl font-black tracking-tight text-white sm:text-4xl">Apports en attente</h1><p class="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Contrôlez les propositions reçues et maintenez les indicateurs de mutualisation à jour.</p></div><div class="rounded-2xl border border-amber-400/20 bg-amber-400/10 px-4 py-3 text-right"><p class="text-2xl font-black text-amber-200">{{ $contributions->total() }}</p><p class="text-[10px] font-bold uppercase tracking-widest text-amber-200/60">À traiter</p></div></div></div>

        <div class="mt-8 flex flex-wrap items-center gap-2 rounded-2xl border border-white/10 bg-white/[0.04] p-2"><span class="px-3 text-[10px] font-black uppercase tracking-widest text-slate-500">Périmètre :</span><button wire:click="$set('typeFilter', 'all')" type="button" class="rounded-xl px-3 py-2 text-xs font-bold transition {{ $typeFilter === 'all' ? 'bg-indigo-500 text-white' : 'text-slate-400 hover:bg-white/10 hover:text-white' }}">Tous</button>@foreach($availableTypes as $type)<button wire:click="$set('typeFilter', '{{ $type }}')" type="button" class="rounded-xl px-3 py-2 text-xs font-bold capitalize transition {{ $typeFilter === $type ? 'bg-indigo-500 text-white' : 'text-slate-400 hover:bg-white/10 hover:text-white' }}">{{ $type }}</button>@endforeach</div>

        <div class="mt-6 overflow-hidden rounded-3xl border border-white/10 bg-white/[0.045] shadow-xl"><div class="hidden grid-cols-[1.3fr_1fr_0.8fr_0.8fr_auto] gap-4 border-b border-white/10 px-6 py-4 text-[10px] font-black uppercase tracking-widest text-slate-500 md:grid"><span>Apporteur</span><span>Projet</span><span>Type</span><span>Valeur</span><span>Action</span></div><div class="divide-y divide-white/10">@forelse($contributions as $contribution)<div wire:key="approval-{{ $contribution->id }}" class="grid gap-4 px-5 py-5 md:grid-cols-[1.3fr_1fr_0.8fr_0.8fr_auto] md:items-center md:px-6"><div><p class="text-sm font-black text-white">{{ $contribution->user?->name ?? 'Utilisateur' }}</p><p class="mt-1 text-xs text-slate-500">{{ $contribution->user?->email }}</p></div><div><p class="text-sm font-bold text-slate-300">{{ $contribution->project?->titre ?? 'Projet supprimé' }}</p><p class="mt-1 line-clamp-1 text-xs text-slate-500">{{ $contribution->description_apport ?: 'Aucun détail fourni' }}</p></div><span class="w-fit rounded-full border px-3 py-1 text-[10px] font-bold uppercase tracking-wider {{ $contribution->type_apport->value === 'financier' ? 'border-emerald-400/20 bg-emerald-400/10 text-emerald-300' : ($contribution->type_apport->value === 'competence' ? 'border-fuchsia-400/20 bg-fuchsia-400/10 text-fuchsia-300' : 'border-amber-400/20 bg-amber-400/10 text-amber-300') }}">{{ $contribution->type_apport->value }}</span><span class="text-sm font-black text-white">{{ $contribution->montant ? number_format((float) $contribution->montant, 0, ',', ' ').' FCFA' : '—' }}</span><div class="flex gap-2"><button wire:click="review({{ $contribution->id }}, 'valide')" type="button" class="rounded-xl bg-emerald-500/15 px-3 py-2 text-[10px] font-black text-emerald-300 transition hover:bg-emerald-500 hover:text-white">Valider</button><button wire:click="review({{ $contribution->id }}, 'refuse')" type="button" class="rounded-xl bg-rose-500/15 px-3 py-2 text-[10px] font-black text-rose-300 transition hover:bg-rose-500 hover:text-white">Refuser</button></div></div>@empty<div class="px-6 py-16 text-center"><p class="text-sm font-bold text-white">Aucune contribution en attente</p><p class="mt-2 text-xs text-slate-500">Toutes les propositions de votre périmètre ont été traitées.</p></div>@endforelse</div></div>
        @if($contributions->hasPages())<div class="mt-6">{{ $contributions->links() }}</div>@endif
    </div>

    @if($showReview)<div class="fixed inset-0 z-[70] flex items-end justify-center bg-slate-950/75 p-0 backdrop-blur-sm sm:items-center sm:p-6"><button wire:click="closeReview" type="button" class="absolute inset-0 cursor-default" aria-label="Fermer"></button><div class="relative w-full max-w-lg rounded-t-3xl border border-white/10 bg-slate-900 p-6 shadow-2xl sm:rounded-3xl sm:p-8"><div class="absolute inset-x-0 top-0 h-1 {{ $decision === 'valide' ? 'bg-emerald-400' : 'bg-rose-400' }}"></div><div class="flex items-start justify-between"><div><p class="text-[10px] font-black uppercase tracking-widest {{ $decision === 'valide' ? 'text-emerald-300' : 'text-rose-300' }}">{{ $decision === 'valide' ? 'Validation' : 'Refus' }}</p><h2 class="mt-2 text-xl font-black text-white">Confirmer votre décision</h2></div><button wire:click="closeReview" type="button" class="rounded-xl p-2 text-slate-500 hover:bg-white/10 hover:text-white">×</button></div><form wire:submit="saveDecision" class="mt-6 space-y-5"><label class="block"><span class="mb-2 block text-xs font-bold text-slate-300">Commentaire / motif @if($decision === 'refuse')<span class="text-rose-400">*</span>@else<span class="font-normal text-slate-600">(optionnel)</span>@endif</span><textarea wire:model.live.debounce.250ms="commentaire" rows="4" placeholder="Expliquez votre décision à l’apporteur..." class="w-full resize-none rounded-2xl border border-white/10 bg-slate-950/70 px-4 py-3.5 text-sm text-white outline-none focus:border-indigo-400/60 focus:ring-4 focus:ring-indigo-500/10 @error('commentaire') border-rose-400/70 @enderror"></textarea>@error('commentaire')<span class="mt-2 block text-xs font-medium text-rose-400">{{ $message }}</span>@enderror</label><button wire:loading.attr="disabled" type="submit" class="w-full rounded-2xl {{ $decision === 'valide' ? 'bg-emerald-500 hover:bg-emerald-400' : 'bg-rose-500 hover:bg-rose-400' }} px-5 py-3.5 text-sm font-black text-white transition disabled:opacity-50"><span wire:loading.remove>Confirmer</span><span wire:loading>Traitement...</span></button></form></div></div>@endif
</div>
